# Generated by Django 4.2 on 2023-05-19 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=150, null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, choices=[('Australia', 'Australia'), ('United States', 'United States'), ('Canada', 'Canada'), ('United Kingdom', 'United Kingdom'), ('Norway', 'Norway'), ('Sweden', 'Sweden'), ('Finland', 'Finland'), ('Turkey', 'Turkey'), ('Romania', 'Romania'), ('Poland', 'Poland'), ('Austria', 'Austria'), ('Italy', 'Italy'), ('Germany', 'Germany'), ('Canada', 'Canada'), ('United States of America', 'United States of America'), ('France', 'France'), ('Spain', 'Spain'), ('Portugal', 'Portugal')], max_length=50, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=50, null=True)),
                ('device', models.CharField(blank=True, max_length=100, null=True)),
                ('product', models.CharField(blank=True, choices=[('ultimate', 'ultimate'), ('premium', 'premium'), ('standard', 'standard'), ('basic', 'basic')], max_length=50, null=True)),
                ('message', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_name', models.CharField(blank=True, max_length=50, null=True)),
                ('my_price', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('Fitur_1', models.TextField(blank=True, max_length=150, null=True)),
                ('Fitur_2', models.TextField(blank=True, max_length=150, null=True)),
                ('Fitur_3', models.TextField(blank=True, max_length=150, null=True)),
                ('Fitur_4', models.TextField(blank=True, max_length=150, null=True)),
                ('Fitur_5', models.TextField(blank=True, max_length=150, null=True)),
                ('Fitur_6', models.TextField(blank=True, max_length=150, null=True)),
                ('Fitur_7', models.TextField(blank=True, max_length=150, null=True)),
                ('Fitur_8', models.TextField(blank=True, max_length=150, null=True)),
                ('Fitur_9', models.TextField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
